[program:zircon-server]
user=root
directory=/home/chairong/server/zircon/
command=/home/chairong/server/zircon/zircon-server
stdout_logfile=/home/chairong/server/zircon/logfile/stdout.log
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 5
stderr_logfile=/home/chairong/server/zircon/logfile/stderr.log
stderr_logfile_maxbytes = 20MB
stderr_logfile_backups = 5